### ISSUE TITLE
Frontpage - Bottom padding on mobile

### ISSUE THREAD

**Issue by ChrisLaganiere** [uclaradio/uclaradio#47]
There's not enough spacing at the bottom of the frontpage content for the stream bar... It works okay on desktop, but there's no padding on mobile:

<img width="400" src="https://cloud.githubusercontent.com/assets/2042745/20377941/dccf133c-ac47-11e6-89a4-d0b9f942a49c.PNG">

Relevant files might be:

`/react/frontpage.jsx`
`/public/css/radio.css`

Affects all the content pages of our new frontpage, so pretty high priority ☝️

**Comment by hsuregan** [comment]
Also note that the size of the boxes will change depending on the content length!

**Comment by kianadk** [comment]
I ended up fixing this within the Events branch since the bug doesn't really show up with the waterfall content in the main branch...here's the commit: https://github.com/uclaradio/uclaradio/commit/b1d58242d8c8fc266824cdc485cb9ecffba204e9
oh, and it wasn't mobile that was the problem--it was Safari 😅

**Comment by ChrisLaganiere** [comment]
Perfect, thank you for fixing 👍
